<!-- Migrated from specs/scind-shell-integration.md:150-344 -->
<!-- Rewritten for the scind-compose binary (RL-112); the sourced function and
     the compose-prefix eval contract are retired -->
<!-- Extraction ID: spec-shell-scripts-bash -->

# =============================================================================
# Scind Shell Integration for Bash
# Generated by: scind init-shell bash
# =============================================================================
#
# scind-compose is a real executable on PATH. Nothing here defines it — this
# file only registers completion.

# -----------------------------------------------------------------------------
# Standard Scind CLI Completion
# -----------------------------------------------------------------------------
# Generated by Cobra's built-in completion.
# Uncomment the following line once the scind binary is built:
# eval "$(scind completion bash)"

# -----------------------------------------------------------------------------
# Completion for scind-compose
# Delegates to the docker binary's Cobra completion protocol
# -----------------------------------------------------------------------------

# Degraded path: used when `docker __complete` is unavailable or reports an
# error. Offers subcommands only — never service names or per-subcommand flags,
# because those cannot be known without asking Docker.
_scind_compose_fallback() {
    local cur="${COMP_WORDS[COMP_CWORD]}"
    COMPREPLY=($(compgen -W "\
build config cp create down events exec images kill logs ls pause port ps \
pull push restart rm run start stop top unpause up version watch" -- "$cur"))
}

_scind_compose_completions() {
    local cur prev out directive lastLine
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD - 1]}"

    # Values for Scind's own targeting flags come from Scind, not Docker
    case "$prev" in
        -w | --workspace)
            COMPREPLY=($(compgen -W "$(scind workspace list -q 2>/dev/null)" -- "$cur"))
            return
            ;;
        -a | --app)
            COMPREPLY=($(compgen -W "$(scind app list -q 2>/dev/null)" -- "$cur"))
            return
            ;;
    esac

    # Build the completion request as if the user had typed "docker compose ...",
    # dropping the leading -w/-a pairs that scind-compose consumes itself
    local -a args=(docker __complete compose)
    local i=1
    while ((i < COMP_CWORD)); do
        case "${COMP_WORDS[$i]}" in
            -w | --workspace | -a | --app) ((i += 2)) ;;
            --workspace=* | --app=*) ((i++)) ;;
            *) break ;;
        esac
    done
    for ((; i < COMP_CWORD; i++)); do
        args+=("${COMP_WORDS[$i]}")
    done
    # Always pass the word under the cursor, empty or not — an empty final
    # argument is how Cobra is told "complete a new word here"
    args+=("$cur")

    out=$("${args[@]}" 2>/dev/null)
    if [[ -z $out ]]; then
        _scind_compose_fallback
        return
    fi

    # The last line carries the directive, formatted ":N"
    directive=0
    lastLine=$(printf "%s\n" "$out" | tail -1)
    if [[ ${lastLine:0:1} == ":" ]]; then
        directive=${lastLine:1}
        out=$(printf "%s\n" "$out" | sed '$d')
    fi

    # Directive bit 1 = error
    if ((directive & 1)); then
        _scind_compose_fallback
        return
    fi

    # Each line is "value<TAB>description"; keep the value
    local -a completions=()
    local line
    while IFS=$'\n' read -r line; do
        [[ -z $line ]] && continue
        completions+=("${line%%	*}")
    done <<<"$out"

    if [[ ${#completions[@]} -gt 0 ]]; then
        COMPREPLY=($(compgen -W "${completions[*]}" -- "$cur"))
        # Directive bit 2 = no space after completion
        ((directive & 2)) && compopt -o nospace 2>/dev/null
        return
    fi

    _scind_compose_fallback
}

# Register completion
complete -F _scind_compose_completions scind-compose

# -----------------------------------------------------------------------------
# Optional: Short alias (users can uncomment if desired)
# -----------------------------------------------------------------------------
# alias cc='scind-compose'
