<!-- Migrated from specs/scind-shell-integration.md:561-707 -->
<!-- Rewritten for the scind-compose binary (RL-112); the sourced function and
     the compose-prefix eval contract are retired -->
<!-- Extraction ID: spec-shell-scripts-fish -->

# =============================================================================
# Scind Shell Integration for Fish
# Generated by: scind init-shell fish
# =============================================================================
#
# scind-compose is a real executable on PATH. Nothing here defines it — this
# file only registers completion.

# -----------------------------------------------------------------------------
# Standard Scind CLI Completion
# -----------------------------------------------------------------------------
# Generated by Cobra's built-in completion.
# Uncomment the following line once the scind binary is built:
# scind completion fish | source

# -----------------------------------------------------------------------------
# Completion for scind-compose
# Delegates to the docker binary's Cobra completion protocol
# -----------------------------------------------------------------------------

# Degraded path: used when `docker __complete` is unavailable or reports an
# error. Offers subcommands only — never service names or per-subcommand flags.
function __scind_compose_fallback
    printf '%s\n' build config cp create down events exec images kill logs ls \
        pause port ps pull push restart rm run start stop top unpause up \
        version watch
end

function __scind_compose_complete
    set -l tokens (commandline -opc)
    set -l current (commandline -ct)

    # Build the completion request as if the user had typed "docker compose ...",
    # dropping the leading -w/-a pairs that scind-compose consumes itself
    set -l args docker __complete compose
    set -l i 2
    while test $i -le (count $tokens)
        switch $tokens[$i]
            case -w --workspace -a --app
                set i (math $i + 2)
            case '--workspace=*' '--app=*'
                set i (math $i + 1)
            case '*'
                break
        end
    end
    while test $i -le (count $tokens)
        set -a args $tokens[$i]
        set i (math $i + 1)
    end
    # Always pass the word under the cursor, empty or not — an empty final
    # argument is how Cobra is told "complete a new word here"
    set -a args "$current"

    set -l out ($args 2>/dev/null)
    if test (count $out) -eq 0
        __scind_compose_fallback
        return
    end

    # The last line carries the directive, formatted ":N"
    set -l directive 0
    if string match -qr '^:' -- $out[-1]
        set directive (string sub -s 2 -- $out[-1])
        set out $out[1..-2]
    end

    # Directive bit 1 = error
    if test (math "$directive % 2") -eq 1
        __scind_compose_fallback
        return
    end

    if test (count $out) -eq 0
        __scind_compose_fallback
        return
    end

    # Each line is "value<TAB>description" — fish's own completion format
    printf '%s\n' $out
end

# Scind's own targeting flags: values come from Scind, not Docker
complete -c scind-compose -s w -l workspace -d "Specify workspace" -xa "(scind workspace list -q 2>/dev/null)"
complete -c scind-compose -s a -l app -d "Specify application" -xa "(scind app list -q 2>/dev/null)"

# Delegate everything else to docker compose completion
complete -c scind-compose -a "(__scind_compose_complete)"

# -----------------------------------------------------------------------------
# Optional: Short abbreviation (users can uncomment if desired)
# -----------------------------------------------------------------------------
# abbr -a cc scind-compose
