<!-- Migrated from specs/scind-shell-integration.md:350-555 -->
<!-- Rewritten for the scind-compose binary (RL-112); the sourced function and
     the compose-prefix eval contract are retired -->
<!-- Extraction ID: spec-shell-scripts-zsh -->

# =============================================================================
# Scind Shell Integration for Zsh
# Generated by: scind init-shell zsh
# =============================================================================
#
# scind-compose is a real executable on PATH. Nothing here defines it — this
# file only registers completion.

# -----------------------------------------------------------------------------
# Standard Scind CLI Completion
# -----------------------------------------------------------------------------
# Generated by Cobra's built-in completion.
# Uncomment the following line once the scind binary is built:
# eval "$(scind completion zsh)"

# -----------------------------------------------------------------------------
# Completion for scind-compose
# Delegates to the docker binary's Cobra completion protocol
# -----------------------------------------------------------------------------

# Degraded path: used when `docker __complete` is unavailable or reports an
# error. Offers subcommands only — never service names or per-subcommand flags.
_scind-compose-fallback() {
    local -a subcommands=(
        'build:Build or rebuild services'
        'config:Validate and view the Compose file'
        'cp:Copy files between host and containers'
        'create:Create services'
        'down:Stop and remove containers, networks'
        'events:Receive real time events from containers'
        'exec:Execute a command in a running container'
        'images:List images used by the created containers'
        'kill:Kill containers'
        'logs:View output from containers'
        'ls:List running compose projects'
        'pause:Pause services'
        'port:Print the public port for a port binding'
        'ps:List containers'
        'pull:Pull service images'
        'push:Push service images'
        'restart:Restart services'
        'rm:Remove stopped containers'
        'run:Run a one-off command'
        'start:Start services'
        'stop:Stop services'
        'top:Display the running processes'
        'unpause:Unpause services'
        'up:Create and start containers'
        'version:Show version information'
        'watch:Watch source and rebuild/refresh services'
    )
    _describe 'docker compose command' subcommands
}

_scind-compose() {
    # Values for Scind's own targeting flags come from Scind, not Docker
    case "${words[CURRENT-1]}" in
        -w|--workspace)
            _values 'workspace' ${(f)"$(scind workspace list -q 2>/dev/null)"}
            return
            ;;
        -a|--app)
            _values 'application' ${(f)"$(scind app list -q 2>/dev/null)"}
            return
            ;;
    esac

    # Build the completion request as if the user had typed "docker compose ...",
    # dropping the leading -w/-a pairs that scind-compose consumes itself.
    # Zsh arrays are 1-indexed; words[1] is "scind-compose".
    local -a args=(docker __complete compose)
    local i=2
    while (( i < CURRENT )); do
        case "${words[$i]}" in
            -w|--workspace|-a|--app) (( i += 2 )) ;;
            --workspace=*|--app=*) (( i++ )) ;;
            *) break ;;
        esac
    done
    for (( ; i < CURRENT; i++ )); do
        args+=("${words[$i]}")
    done
    # Always pass the word under the cursor, empty or not — an empty final
    # argument is how Cobra is told "complete a new word here"
    args+=("${words[CURRENT]}")

    local out
    out=$("${args[@]}" 2>/dev/null)
    if [[ -z "$out" ]]; then
        _scind-compose-fallback
        return
    fi

    # The last line carries the directive, formatted ":N"
    local -a lines=("${(@f)out}")
    local directive=0
    if [[ "${lines[-1]}" == :* ]]; then
        directive="${lines[-1]#:}"
        lines=("${lines[@]:0:-1}")
    fi

    # Directive bit 1 = error
    if (( directive & 1 )); then
        _scind-compose-fallback
        return
    fi

    # Each line is "value<TAB>description" — the shape _describe expects once
    # the tab becomes a colon
    local -a completions=()
    local line
    for line in "${lines[@]}"; do
        [[ -z "$line" ]] && continue
        completions+=("${line/$'\t'/:}")
    done

    if (( ${#completions[@]} == 0 )); then
        _scind-compose-fallback
        return
    fi

    # Directive bit 2 = no space after completion
    if (( directive & 2 )); then
        _describe -o nospace 'docker compose' completions
    else
        _describe 'docker compose' completions
    fi
}

# Register completion
compdef _scind-compose scind-compose

# -----------------------------------------------------------------------------
# Optional: Short alias (users can uncomment if desired)
# -----------------------------------------------------------------------------
# alias cc='scind-compose'
