<!-- Migrated from specs/scind-shell-integration.md:350-555 -->
<!-- Extraction ID: spec-shell-scripts-zsh -->

# =============================================================================
# Scind Shell Integration for Zsh
# Generated by: scind init-shell zsh
# =============================================================================

# -----------------------------------------------------------------------------
# Standard Scind CLI Completion
# -----------------------------------------------------------------------------
# Generated by Cobra's built-in completion.
# Uncomment the following line once the scind binary is built:
# eval "$(scind completion zsh)"

# -----------------------------------------------------------------------------
# scind-compose: Docker Compose Passthrough with Context Awareness
# -----------------------------------------------------------------------------

scind-compose() {
    local prefix
    local -a prefix_args=()
    local -a passthrough_args=()
    local parsing_scind_flags=true

    # Parse arguments: extract -w/-a flags for scind, pass rest through
    while [[ $# -gt 0 ]]; do
        if $parsing_scind_flags; then
            case "$1" in
                -w|--workspace)
                    prefix_args+=("$1" "$2")
                    shift 2
                    ;;
                --workspace=*)
                    prefix_args+=("$1")
                    shift
                    ;;
                -a|--app)
                    prefix_args+=("$1" "$2")
                    shift 2
                    ;;
                --app=*)
                    prefix_args+=("$1")
                    shift
                    ;;
                -*)
                    # Unknown flag - might be for docker compose
                    parsing_scind_flags=false
                    passthrough_args+=("$1")
                    shift
                    ;;
                *)
                    # Positional argument - stop parsing scind flags
                    parsing_scind_flags=false
                    passthrough_args+=("$1")
                    shift
                    ;;
            esac
        else
            passthrough_args+=("$1")
            shift
        fi
    done

    # Get the docker compose prefix from scind
    prefix=$(scind compose-prefix "${prefix_args[@]}" 2>/dev/null)
    if [[ -z "$prefix" ]]; then
        # Run again to show the error message
        scind compose-prefix "${prefix_args[@]}"
        return 1
    fi

    # Execute: eval handles the quoted paths in prefix correctly
    eval "$prefix" '"${passthrough_args[@]}"'
}

# -----------------------------------------------------------------------------
# Completion for scind-compose
# Delegates to Docker's completion with transformed context
# -----------------------------------------------------------------------------

_scind-compose() {
    local -a prefix_cmd_args=()
    local -a docker_words=()
    local parsing_scind_flags=true
    local i=2  # words[1] is "scind-compose" in zsh (1-indexed)

    # Extract scind-specific flags, pass rest to docker
    while [[ $i -le ${#words[@]} ]]; do
        if $parsing_scind_flags; then
            case "${words[$i]}" in
                -w|--workspace)
                    prefix_cmd_args+=("${words[$i]}" "${words[$((i+1))]}")
                    ((i += 2))
                    ;;
                --workspace=*)
                    prefix_cmd_args+=("${words[$i]}")
                    ((i++))
                    ;;
                -a|--app)
                    prefix_cmd_args+=("${words[$i]}" "${words[$((i+1))]}")
                    ((i += 2))
                    ;;
                --app=*)
                    prefix_cmd_args+=("${words[$i]}")
                    ((i++))
                    ;;
                -*)
                    parsing_scind_flags=false
                    docker_words+=("${words[$i]}")
                    ((i++))
                    ;;
                *)
                    parsing_scind_flags=false
                    docker_words+=("${words[$i]}")
                    ((i++))
                    ;;
            esac
        else
            docker_words+=("${words[$i]}")
            ((i++))
        fi
    done

    # Get prefix from scind
    local prefix
    prefix=$(scind compose-prefix "${prefix_cmd_args[@]}" 2>/dev/null)
    [[ -z "$prefix" ]] && return 1

    # Parse prefix into array (respecting quotes)
    # (z) splits like shell words, (@Q) removes quotes while preserving array
    local -a prefix_words
    prefix_words=("${(@Q)${(z)prefix}}")

    # Build fake command line for docker's completion
    # Zsh arrays are 1-indexed, CURRENT is 1-indexed position
    #
    # Original: scind-compose exec php
    #   words=("scind-compose" "exec" "php") CURRENT=3 (or 4 if completing new word)
    #
    # Fake: docker compose -p X -f Y exec php
    #   words=("docker" "compose" "-p" "X" "-f" "Y" "exec" "php")

    local -a fake_words=("${prefix_words[@]}" "${docker_words[@]}")

    # Calculate new CURRENT position
    # Original CURRENT is relative to words array
    # We need to map it to the fake_words array
    local words_before_docker=$((CURRENT - 1))  # How many words typed (excluding current)
    local scind_flags_consumed=$((${#words[@]} - 1 - ${#docker_words[@]}))
    local fake_current=$((${#prefix_words[@]} + ${#docker_words[@]}))

    # If we're in the middle of typing a word, adjust
    if [[ $CURRENT -le ${#words[@]} ]] && [[ -n "${words[$CURRENT]}" ]]; then
        fake_current=$((${#prefix_words[@]} + CURRENT - 1 - scind_flags_consumed))
    fi

    # Override completion context
    words=("${fake_words[@]}")
    CURRENT=$fake_current

    # Try to find docker's completion function
    # It might be _docker, _docker-compose, or loaded on demand
    if (( $+functions[_docker] )); then
        _docker
    elif (( $+functions[_docker-compose] )); then
        _docker-compose
    else
        # Fallback: basic subcommand completion
        if [[ ${#docker_words[@]} -eq 0 ]]; then
            local -a subcommands=(
                'build:Build or rebuild services'
                'config:Validate and view the Compose file'
                'create:Create services'
                'down:Stop and remove containers, networks'
                'events:Receive real time events from containers'
                'exec:Execute a command in a running container'
                'images:List images used by the created containers'
                'kill:Kill containers'
                'logs:View output from containers'
                'pause:Pause services'
                'port:Print the public port for a port binding'
                'ps:List containers'
                'pull:Pull service images'
                'push:Push service images'
                'restart:Restart services'
                'rm:Remove stopped containers'
                'run:Run a one-off command'
                'start:Start services'
                'stop:Stop services'
                'top:Display the running processes'
                'unpause:Unpause services'
                'up:Create and start containers'
                'version:Show version information'
            )
            _describe 'docker compose command' subcommands
        fi
    fi
}

# Register completion
compdef _scind-compose scind-compose

# -----------------------------------------------------------------------------
# Optional: Short alias (users can uncomment if desired)
# -----------------------------------------------------------------------------
# alias cc='scind-compose'
