<!-- Migrated from specs/contrail-shell-integration.md:150-344 -->
<!-- Extraction ID: spec-shell-scripts-bash -->

# =============================================================================
# Contrail Shell Integration for Bash
# Generated by: contrail init-shell bash
# =============================================================================

# -----------------------------------------------------------------------------
# Standard Contrail CLI Completion
# -----------------------------------------------------------------------------
# Generated by Cobra's built-in completion.
# Uncomment the following line once the contrail binary is built:
# eval "$(contrail completion bash)"

# -----------------------------------------------------------------------------
# contrail-compose: Docker Compose Passthrough with Context Awareness
# -----------------------------------------------------------------------------

contrail-compose() {
    local prefix
    local -a prefix_args=()
    local -a passthrough_args=()
    local parsing_contrail_flags=true

    # Parse arguments: extract -w/-a flags for contrail, pass rest through
    while [[ $# -gt 0 ]]; do
        if $parsing_contrail_flags; then
            case "$1" in
                -w|--workspace)
                    prefix_args+=("$1" "$2")
                    shift 2
                    ;;
                --workspace=*)
                    prefix_args+=("$1")
                    shift
                    ;;
                -a|--app)
                    prefix_args+=("$1" "$2")
                    shift 2
                    ;;
                --app=*)
                    prefix_args+=("$1")
                    shift
                    ;;
                -*)
                    # Unknown flag - might be for docker compose
                    parsing_contrail_flags=false
                    passthrough_args+=("$1")
                    shift
                    ;;
                *)
                    # Positional argument - stop parsing contrail flags
                    parsing_contrail_flags=false
                    passthrough_args+=("$1")
                    shift
                    ;;
            esac
        else
            passthrough_args+=("$1")
            shift
        fi
    done

    # Get the docker compose prefix from contrail
    prefix=$(contrail compose-prefix "${prefix_args[@]}" 2>/dev/null)
    if [[ -z "$prefix" ]]; then
        # Run again to show the error message
        contrail compose-prefix "${prefix_args[@]}"
        return 1
    fi

    # Execute: eval handles the quoted paths in prefix correctly
    eval "$prefix" '"${passthrough_args[@]}"'
}

# -----------------------------------------------------------------------------
# Completion for contrail-compose
# Delegates to Docker's completion with transformed context
# -----------------------------------------------------------------------------

_contrail_compose_completions() {
    local cur prev words cword
    _init_completion || return

    # Extract contrail-specific flags to pass to compose-prefix
    local -a prefix_cmd_args=()
    local -a docker_words=()
    local parsing_contrail_flags=true
    local i=1  # Skip words[0] which is "contrail-compose"

    while [[ $i -lt ${#words[@]} ]]; do
        if $parsing_contrail_flags; then
            case "${words[$i]}" in
                -w|--workspace)
                    prefix_cmd_args+=("${words[$i]}" "${words[$((i+1))]}")
                    ((i += 2))
                    ;;
                --workspace=*)
                    prefix_cmd_args+=("${words[$i]}")
                    ((i++))
                    ;;
                -a|--app)
                    prefix_cmd_args+=("${words[$i]}" "${words[$((i+1))]}")
                    ((i += 2))
                    ;;
                --app=*)
                    prefix_cmd_args+=("${words[$i]}")
                    ((i++))
                    ;;
                -*)
                    parsing_contrail_flags=false
                    docker_words+=("${words[$i]}")
                    ((i++))
                    ;;
                *)
                    parsing_contrail_flags=false
                    docker_words+=("${words[$i]}")
                    ((i++))
                    ;;
            esac
        else
            docker_words+=("${words[$i]}")
            ((i++))
        fi
    done

    # Get prefix from contrail
    local prefix
    prefix=$(contrail compose-prefix "${prefix_cmd_args[@]}" 2>/dev/null)
    [[ -z "$prefix" ]] && return

    # Parse prefix into an array (handles quoted paths)
    local -a prefix_words
    eval "prefix_words=($prefix)"

    # Build fake command line for docker's completion
    # Original: contrail-compose exec php
    # Fake:     docker compose -p X -f Y exec php
    local -a fake_words=("${prefix_words[@]}" "${docker_words[@]}")
    local fake_cword=$(( ${#prefix_words[@]} + ${#docker_words[@]} - 1 ))

    # Adjust fake_cword if we're completing a new word
    if [[ -z "$cur" ]] || [[ "$cur" != "${words[$cword]}" ]]; then
        ((fake_cword++))
    fi

    # Check if docker completion function exists
    if ! declare -F _docker &>/dev/null; then
        # Fallback: try to load docker completion
        if [[ -f /usr/share/bash-completion/completions/docker ]]; then
            source /usr/share/bash-completion/completions/docker
        elif [[ -f /etc/bash_completion.d/docker ]]; then
            source /etc/bash_completion.d/docker
        elif [[ -f "$(brew --prefix 2>/dev/null)/etc/bash_completion.d/docker" ]]; then
            source "$(brew --prefix)/etc/bash_completion.d/docker"
        fi
    fi

    # If still no docker completion, provide basic subcommand completion
    if ! declare -F _docker &>/dev/null; then
        if [[ ${#docker_words[@]} -eq 0 ]]; then
            COMPREPLY=($(compgen -W "build config create down events exec images kill logs pause port ps pull push restart rm run start stop top unpause up version" -- "$cur"))
        fi
        return
    fi

    # Save original completion context
    local orig_cword=$cword
    local -a orig_words=("${words[@]}")

    # Override with fake context
    words=("${fake_words[@]}")
    cword=$fake_cword
    COMP_WORDS=("${fake_words[@]}")
    COMP_CWORD=$fake_cword
    COMP_LINE="${fake_words[*]}"
    COMP_POINT=${#COMP_LINE}

    # Invoke docker's completion
    _docker

    # Restore original context (defensive)
    words=("${orig_words[@]}")
    cword=$orig_cword
}

# Register completion
complete -F _contrail_compose_completions contrail-compose

# -----------------------------------------------------------------------------
# Optional: Short alias (users can uncomment if desired)
# -----------------------------------------------------------------------------
# alias cc='contrail-compose'
