<!-- Migrated from specs/scind-shell-integration.md:561-707 -->
<!-- Extraction ID: spec-shell-scripts-fish -->

# =============================================================================
# Scind Shell Integration for Fish
# Generated by: scind init-shell fish
# =============================================================================

# -----------------------------------------------------------------------------
# Standard Scind CLI Completion
# -----------------------------------------------------------------------------
# Generated by Cobra's built-in completion.
# Uncomment the following line once the scind binary is built:
# scind completion fish | source

# -----------------------------------------------------------------------------
# scind-compose: Docker Compose Passthrough with Context Awareness
# -----------------------------------------------------------------------------

function scind-compose --description "Docker Compose with Scind context awareness"
    set -l prefix_args
    set -l passthrough_args
    set -l parsing_scind_flags true

    # Parse arguments: extract -w/-a flags for scind, pass rest through
    set -l i 1
    while test $i -le (count $argv)
        if test "$parsing_scind_flags" = true
            switch $argv[$i]
                case -w --workspace
                    set -a prefix_args $argv[$i] $argv[(math $i + 1)]
                    set i (math $i + 2)
                case '--workspace=*'
                    set -a prefix_args $argv[$i]
                    set i (math $i + 1)
                case -a --app
                    set -a prefix_args $argv[$i] $argv[(math $i + 1)]
                    set i (math $i + 2)
                case '--app=*'
                    set -a prefix_args $argv[$i]
                    set i (math $i + 1)
                case '-*'
                    # Unknown flag - might be for docker compose
                    set parsing_scind_flags false
                    set -a passthrough_args $argv[$i]
                    set i (math $i + 1)
                case '*'
                    # Positional argument - stop parsing scind flags
                    set parsing_scind_flags false
                    set -a passthrough_args $argv[$i]
                    set i (math $i + 1)
            end
        else
            set -a passthrough_args $argv[$i]
            set i (math $i + 1)
        end
    end

    # Get the docker compose prefix from scind
    set -l prefix (scind compose-prefix $prefix_args 2>/dev/null)
    if test -z "$prefix"
        # Run again to show the error message
        scind compose-prefix $prefix_args
        return 1
    end

    # Execute: eval handles the quoted paths in prefix correctly
    eval $prefix $passthrough_args
end

# -----------------------------------------------------------------------------
# Completion for scind-compose
# Uses fish's complete -C to delegate to docker's completion
# -----------------------------------------------------------------------------

function __scind_compose_complete
    # Get the current command line tokens
    set -l tokens (commandline -opc)

    # Extract scind-specific flags, build docker command
    set -l prefix_args
    set -l docker_args
    set -l parsing_scind_flags true
    set -l i 2  # Skip "scind-compose"

    while test $i -le (count $tokens)
        if test "$parsing_scind_flags" = true
            switch $tokens[$i]
                case -w --workspace
                    set -a prefix_args $tokens[$i] $tokens[(math $i + 1)]
                    set i (math $i + 2)
                case '--workspace=*'
                    set -a prefix_args $tokens[$i]
                    set i (math $i + 1)
                case -a --app
                    set -a prefix_args $tokens[$i] $tokens[(math $i + 1)]
                    set i (math $i + 2)
                case '--app=*'
                    set -a prefix_args $tokens[$i]
                    set i (math $i + 1)
                case '-*'
                    set parsing_scind_flags false
                    set -a docker_args $tokens[$i]
                    set i (math $i + 1)
                case '*'
                    set parsing_scind_flags false
                    set -a docker_args $tokens[$i]
                    set i (math $i + 1)
            end
        else
            set -a docker_args $tokens[$i]
            set i (math $i + 1)
        end
    end

    # Get prefix from scind
    set -l prefix (scind compose-prefix $prefix_args 2>/dev/null | string split ' ')
    if test -z "$prefix"
        return
    end

    # Build fake command line and get completions
    # The trailing space is important - it tells fish we're completing the next word
    set -l fake_line (string join ' ' $prefix $docker_args)

    # Check if we're completing a partial word
    set -l current_token (commandline -ct)
    if test -n "$current_token"
        set fake_line "$fake_line$current_token"
    else
        set fake_line "$fake_line "
    end

    # Use fish's built-in completion delegation
    complete -C "$fake_line"
end

# Provide scind-specific flag completions first
complete -c scind-compose -s w -l workspace -d "Specify workspace" -xa "(scind workspace list -q 2>/dev/null)"
complete -c scind-compose -s a -l app -d "Specify application" -xa "(scind app list -q 2>/dev/null)"

# Delegate everything else to docker compose completion
complete -c scind-compose -a "(__scind_compose_complete)"

# -----------------------------------------------------------------------------
# Optional: Short abbreviation (users can uncomment if desired)
# -----------------------------------------------------------------------------
# abbr -a cc scind-compose
