#!/usr/bin/env zsh
# =============================================================================
# Contrail Shell Integration for Zsh
# Generated by: contrail init-shell zsh
# =============================================================================

# -----------------------------------------------------------------------------
# Standard Contrail CLI Completion
# -----------------------------------------------------------------------------
# Uncomment the following line once the contrail binary is built:
# eval "$(contrail completion zsh)"

# -----------------------------------------------------------------------------
# contrail-compose: Docker Compose Passthrough with Context Awareness
# -----------------------------------------------------------------------------

contrail-compose() {
    local prefix
    local -a prefix_args=()
    local -a passthrough_args=()
    local parsing_contrail_flags=true

    # Parse arguments: extract -w/-a flags for contrail, pass rest through
    while [[ $# -gt 0 ]]; do
        if $parsing_contrail_flags; then
            case "$1" in
                -w|--workspace)
                    prefix_args+=("$1" "$2")
                    shift 2
                    ;;
                --workspace=*)
                    prefix_args+=("$1")
                    shift
                    ;;
                -a|--app)
                    prefix_args+=("$1" "$2")
                    shift 2
                    ;;
                --app=*)
                    prefix_args+=("$1")
                    shift
                    ;;
                -*)
                    # Unknown flag - might be for docker compose
                    parsing_contrail_flags=false
                    passthrough_args+=("$1")
                    shift
                    ;;
                *)
                    # Positional argument - stop parsing contrail flags
                    parsing_contrail_flags=false
                    passthrough_args+=("$1")
                    shift
                    ;;
            esac
        else
            passthrough_args+=("$1")
            shift
        fi
    done

    # Get the docker compose prefix from contrail
    prefix=$(contrail compose-prefix "${prefix_args[@]}" 2>/dev/null)
    if [[ -z "$prefix" ]]; then
        # Run again to show the error message
        contrail compose-prefix "${prefix_args[@]}"
        return 1
    fi

    # Execute: eval handles the quoted paths in prefix correctly
    eval "$prefix" '"${passthrough_args[@]}"'
}

# -----------------------------------------------------------------------------
# Completion for contrail-compose
# Delegates to Docker's completion with transformed context
# -----------------------------------------------------------------------------

_contrail-compose() {
    local -a prefix_cmd_args=()
    local -a docker_words=()
    local parsing_contrail_flags=true
    local i=2  # words[1] is "contrail-compose" in zsh (1-indexed)

    # Extract contrail-specific flags, pass rest to docker
    while [[ $i -le ${#words[@]} ]]; do
        if $parsing_contrail_flags; then
            case "${words[$i]}" in
                -w|--workspace)
                    prefix_cmd_args+=("${words[$i]}" "${words[$((i+1))]}")
                    ((i += 2))
                    ;;
                --workspace=*)
                    prefix_cmd_args+=("${words[$i]}")
                    ((i++))
                    ;;
                -a|--app)
                    prefix_cmd_args+=("${words[$i]}" "${words[$((i+1))]}")
                    ((i += 2))
                    ;;
                --app=*)
                    prefix_cmd_args+=("${words[$i]}")
                    ((i++))
                    ;;
                -*)
                    parsing_contrail_flags=false
                    docker_words+=("${words[$i]}")
                    ((i++))
                    ;;
                *)
                    parsing_contrail_flags=false
                    docker_words+=("${words[$i]}")
                    ((i++))
                    ;;
            esac
        else
            docker_words+=("${words[$i]}")
            ((i++))
        fi
    done

    # Get prefix from contrail
    local prefix
    prefix=$(contrail compose-prefix "${prefix_cmd_args[@]}" 2>/dev/null)
    [[ -z "$prefix" ]] && return 1

    # Parse prefix into array (respecting quotes)
    local -a prefix_words
    prefix_words=("${(@Q)${(z)prefix}}")

    # Build fake command line for docker's completion
    local -a fake_words=("${prefix_words[@]}" "${docker_words[@]}")

    # Calculate new CURRENT position
    local words_before_docker=$((CURRENT - 1))
    local contrail_flags_consumed=$((${#words[@]} - 1 - ${#docker_words[@]}))
    local fake_current=$((${#prefix_words[@]} + ${#docker_words[@]}))

    # If we're in the middle of typing a word, adjust
    if [[ $CURRENT -le ${#words[@]} ]] && [[ -n "${words[$CURRENT]}" ]]; then
        fake_current=$((${#prefix_words[@]} + CURRENT - 1 - contrail_flags_consumed))
    fi

    # Override completion context
    words=("${fake_words[@]}")
    CURRENT=$fake_current

    # Try to find docker's completion function
    if (( $+functions[_docker] )); then
        _docker
    elif (( $+functions[_docker-compose] )); then
        _docker-compose
    else
        # Fallback: basic subcommand completion
        if [[ ${#docker_words[@]} -eq 0 ]]; then
            local -a subcommands=(
                'build:Build or rebuild services'
                'config:Validate and view the Compose file'
                'create:Create services'
                'down:Stop and remove containers, networks'
                'events:Receive real time events from containers'
                'exec:Execute a command in a running container'
                'images:List images used by the created containers'
                'kill:Kill containers'
                'logs:View output from containers'
                'pause:Pause services'
                'port:Print the public port for a port binding'
                'ps:List containers'
                'pull:Pull service images'
                'push:Push service images'
                'restart:Restart services'
                'rm:Remove stopped containers'
                'run:Run a one-off command'
                'start:Start services'
                'stop:Stop services'
                'top:Display the running processes'
                'unpause:Unpause services'
                'up:Create and start containers'
                'version:Show version information'
            )
            _describe 'docker compose command' subcommands
        fi
    fi
}

# Register completion
compdef _contrail-compose contrail-compose

# -----------------------------------------------------------------------------
# Optional: Short alias (users can uncomment if desired)
# -----------------------------------------------------------------------------
# alias cc='contrail-compose'
